import './globals.css'
import Link from 'next/link'
import { ClerkProvider } from '@clerk/nextjs'
import { UserButton, SignInButton, SignedOut } from "@clerk/nextjs";
import React, { useState } from 'react';
import {SongContext} from './song_context.js';

export const metadata = {
  title: 'SSM Songbook',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className="dark:bg-gray-800 dark:text-white">
      <div id="header" className="box-border justify-between flex items-center h-14 pl-0.6% pr-0.6% pt-10 pb-8 mx-auto w-11/12">
        <div className="box-border flex items-center">
          <img id="ssm_icon" src="./ssm_icon.png" className="box-border inline-block h-8 mr-3"/>
          <h1 className="inline-block m-0 p-0 text-3xl font-extrabold text-gray-800 dark:text-white">songbook</h1>
        </div>
        <div className="flex">
          <Link className ="mx-2 my-auto h-fit items-center hover:text-gray-400 focus:underline focus:font-bold" href="./" tabIndex={0}>Create Set</Link>
          <p className="my-auto">/</p>
          <Link className ="mx-2 my-auto h-fit items-center hover:text-gray-400 focus:underline focus:font-bold" href="/song_library" tabIndex={0}>Song Library</Link>
          <p className="my-auto">/</p>
          <Link className ="mx-2 my-auto h-fit items-center hover:text-gray-400 focus:underline focus:font-bold" href="/media_mode" tabIndex={0}>Media Mode</Link>
          <UserButton appearance={{
            elements: {
              rootBox: 'inline-block mx-2 align-bottom'}}}/>
          <SignedOut>
            <SignInButton mode="modal">
            <button className="box-border inline-block font-semibold text-white text-sm p-2 ml-3 bg-ssmblue800 rounded-md hover:bg-ssmbluenight active:bg-ssmbluenight">Sign In</button>
            </SignInButton>
          </SignedOut>
        </div>
      </div>
        {children}
      </body>
    </html>
  </ClerkProvider>
  )
}